[build]
  functions = "service"

[[redirects]]
  from = "/people*"
  to = "/"
  status = 200

[template.environment]
  REACT_APP_DOMAIN = "Auth0 domain"
  REACT_APP_CLIENT_ID= "Auth0 Client ID"
  REACT_APP_AUDIENCE = "Auth0 API audience"
  REACT_APP_POLICY_NAME = "Policy name"
  TENANT_ID = "Aserto tenant ID"
  AUTHORIZER_API_KEY = "Aserto tenant API key"

[context.production]
  environment = { REACT_APP_NETLIFY = "NETLIFY" }