[build]
  functions = "service"

[[redirects]]
  from = "/people*"
  to = "/"
  status = 200

[template.environment]
  REACT_APP_DOMAIN = "enter your Auth0 domain - <name.region.auth0.com>"
  REACT_APP_CLIENT_ID= "enter your Auth0 application's Client ID"
  REACT_APP_AUDIENCE = "enter the audience you configured for your Auth0 API"
  REACT_APP_POLICY_NAME = "set to the policy name"
  TENANT_ID = "enter your Aserto tenant ID, found in the policy details"
  AUTHORIZER_API_KEY = "enter your Aserto tenant's API key, found in the policy details"
